# Intro To PyEntr and the ENTR Runtime

This notebook showcases the PyEntr Connection classes, the openoa from_entr() constructor, the openoa schema module, and describes the current implementation and future vision of these software.

## 1. Directly querying the warehouse with PyEntr

PyEntr, which is developed [here](https://github.com/entralliance/py-entr) contains a module, `entr.connection` that helps you connect to the ENTR warehouse and start querying it quickly and easily. PyEntr is pre-installed in the ENTR runtime, so assuming you are within the ENTR Runtime, you can simply run:

In [2]:
import entr.connection

### Querying from the built in Spark warehouse

In [3]:
conn = entr.connection.PySparkEntrConnection()

In [15]:
conn.pandas_query("show tables;")[:8]

        namespace                     tableName  isTemporary
0  entr_warehouse  dim_asset_reanalysis_dataset        False
1  entr_warehouse          dim_asset_wind_plant        False
2  entr_warehouse        dim_asset_wind_turbine        False
3  entr_warehouse                dim_entr_asset        False
4  entr_warehouse             dim_entr_tag_list        False
5  entr_warehouse           fct_entr_plant_data        False
6  entr_warehouse      fct_entr_reanalysis_data        False
7  entr_warehouse          fct_entr_time_series        False

In [6]:
conn.pandas_query("select * from dim_asset_wind_plant limit 10;")

,plant_id,plant_name,latitude,longitude,plant_capacity,number_of_turbines,turbine_capacity
0,1,La Haute Borne,48.452000,5.588000,8.200000,4,2.050000

## Using the openoa.PlantData.from_entr constructor

OpenOA, developed [here](https://github.com/NREL/OpenOA), is NREL's open source operational analysis python package for wind power plants. OpenOA is distributed with the ENTR Runtime, and comes pre-installed and configured there. A core component of OpenOA is the PlantData data model. The PlantData data model is implemented in OpenOA as a python class containing several Pandas data frames. More information about the OpenOA PlantData data model can be found in the [OpenOA documentation](http://openoa.readthedocs.io). 

PyEntr provides a PlantData constructor which can load data directly from an ENTR warehouse into the OpenOA PlantData data model for analysis. This function is located at `entr.plantdata.from_entr`, and is automatically attached to `openoa.PlantData.from_entr` using a thin-wrapper method if PyEntr is installed.

In [7]:
import openoa

In [8]:
plant = openoa.PlantData.from_entr("La Haute Borne", schema="MonteCarloAEP")

{'meter': {'columns': ['MMTR_SupWh'], 'freq': ('MS', 'W', 'D', 'H', 'T', 'min', 'S', 'L', 'ms', 'U', 'us', 'N')}, 'curtail': {'columns': ['IAVL_DnWh', 'IAVL_ExtPwrDnWh'], 'freq': ('MS', 'W', 'D', 'H', 'T', 'min', 'S', 'L', 'ms', 'U', 'us', 'N')}, 'reanalysis': {'columns': ['WMETR_HorWdSpd', 'WMETR_AirDen'], 'conditional_columns': {'reg_temperature': ['WMETR_EnvTmp'], 'reg_wind_direction': ['WMETR_HorWdSpdU', 'WMETR_HorWdSpdV']}, 'freq': ('MS', 'W', 'D', 'H', 'T', 'min', 'S', 'L', 'ms', 'U', 'us', 'N')}}
meter
'MMTR.SupWh'
SELECT interval_s, value_type, value_units FROM openoa_revenue_meter_tag_metadata WHERE entr_tag_name in ('MMTR.SupWh');
   interval_s value_type value_units
0  600.000000        sum         kWh
SELECT float(`MMTR.SupWh`) as MMTR_SupWh , date_time as time FROM openoa_revenue_meter WHERE plant_id = 1 ORDER BY time;
curtail
'IAVL.DnWh','IAVL.ExtPwrDnWh'
SELECT interval_s, value_type, value_units FROM openoa_curtailment_and_availability_tag_metadata WHERE entr_tag_name in ('IAVL.DnWh','IAVL.ExtPwrDnWh');
   interval_s value_type value_units
0  600.000000        sum         kWh
1  600.000000        sum         kWh
SELECT float(`IAVL.DnWh`) as IAVL_DnWh ,float(`IAVL.ExtPwrDnWh`) as IAVL_ExtPwrDnWh , date_time as time FROM openoa_curtailment_and_availability WHERE plant_id = 1 ORDER BY time;
reanalysis
SELECT float(`WMETR.HorWdSpd`) as WMETR_HorWdSpd ,float(`WMETR.AirDen`) as WMETR_AirDen , date_time as time FROM openoa_reanalysis WHERE plant_id = 1 AND reanalysis_dataset_name = "MERRA2" ORDER BY time;
'WMETR.HorWdSpd','WMETR.AirDen'
SELECT interval_s, value_type, value_units FROM openoa_reanalysis_tag_metadata WHERE entr_tag_name in ('WMETR.HorWdSpd','WMETR.AirDen')AND reanalysis_dataset_name == "MERRA2";
    interval_s value_type value_units
0  3600.000000    average       kg/m³
1  3600.000000    average         m/s
SELECT float(`WMETR.HorWdSpd`) as WMETR_HorWdSpd ,float(`WMETR.AirDen`) as WMETR_AirDen , date_time as time FROM openoa_reanalysis WHERE plant_id = 1 AND reanalysis_dataset_name = "ERA5" ORDER BY time;
'WMETR.HorWdSpd','WMETR.AirDen'
SELECT interval_s, value_type, value_units FROM openoa_reanalysis_tag_metadata WHERE entr_tag_name in ('WMETR.HorWdSpd','WMETR.AirDen')AND reanalysis_dataset_name == "ERA5";
    interval_s value_type value_units
0  3600.000000    average         m/s
1  3600.000000    average       kg/m³
METADATA:
{'latitude': Decimal('48.452000'), 'longitude': Decimal('5.588000'), 'capacity': Decimal('8.200000'), 'number_of_turbines': 4, 'turbine_capacity': Decimal('2.050000'), '_entr_plant_id': 1, 'meter': {'frequency': Timedelta('0 days 00:10:00'), 'time': 'time', 'MMTR_SupWh': 'MMTR_SupWh'}, 'curtail': {'frequency': Timedelta('0 days 00:10:00'), 'time': 'time', 'IAVL_DnWh': 'IAVL_DnWh', 'IAVL_ExtPwrDnWh': 'IAVL_ExtPwrDnWh'}, 'reanalysis': {'merra2': {'frequency': Timedelta('0 days 01:00:00'), 'time': 'time', 'WMETR_HorWdSpd': 'WMETR_HorWdSpd', 'WMETR_AirDen': 'WMETR_AirDen'}, 'era5': {'frequency': Timedelta('0 days 01:00:00'), 'time': 'time', 'WMETR_HorWdSpd': 'WMETR_HorWdSpd', 'WMETR_AirDen': 'WMETR_AirDen'}}}
TABLES:
{'meter':         MMTR_SupWh                time
0       369.726013 2014-01-01 00:00:00
1       376.408997 2014-01-01 00:10:00
2       309.199005 2014-01-01 00:20:00
3       350.175995 2014-01-01 00:30:00
4       286.333008 2014-01-01 00:40:00
...            ...                 ...
105115  147.141006 2015-12-31 23:10:00
105116  194.841995 2015-12-31 23:20:00
105117  180.688004 2015-12-31 23:30:00
105118  149.039001 2015-12-31 23:40:00
105119  125.091003 2015-12-31 23:50:00

[105120 rows x 2 columns], 'curtail':        IAVL_DnWh  IAVL_ExtPwrDnWh                time
0            0.0              0.0 2014-01-01 00:00:00
1            0.0              0.0 2014-01-01 01:00:00
2            0.0              0.0 2014-01-01 02:00:00
3            0.0              0.0 2014-01-01 03:00:00
4            0.0              0.0 2014-01-01 04:00:00
...          ...              ...                 ...
17515        0.0              0.0 2015-12-31 19:00:00
17516        0.0              0.0 2015-12-31 20:00:00
17517        0.0              0.0 2015-12-31 21:00:00
17518        0.0              0.0 2015-12-31 22:00:00
17519        0.0              0.0 2015-12-31 23:00:00

[17520 rows x 3 columns], 'reanalysis': {'merra2':         WMETR_HorWdSpd  WMETR_AirDen                time
0             6.638407      1.184835 2000-09-01 00:30:00
1             7.033765      1.186623 2000-09-01 01:30:00
2             7.400314      1.187641 2000-09-01 02:30:00
3             7.669838      1.188068 2000-09-01 03:30:00
4             7.805313      1.187347 2000-09-01 04:30:00
...                ...           ...                 ...
184075        7.220500      1.192943 2021-08-31 19:30:00
184076        7.248846      1.196421 2021-08-31 20:30:00
184077        7.298179      1.199264 2021-08-31 21:30:00
184078        7.335604      1.201840 2021-08-31 22:30:00
184079        7.245415      1.204394 2021-08-31 23:30:00

[184080 rows x 3 columns], 'era5':         WMETR_HorWdSpd  WMETR_AirDen                time
0             7.370232      1.216079 2001-03-01 00:00:00
1             7.801492      1.217739 2001-03-01 01:00:00
2             8.044068      1.218205 2001-03-01 02:00:00
3             7.955197      1.218263 2001-03-01 03:00:00
4             7.789466      1.217996 2001-03-01 04:00:00
...                ...           ...                 ...
184075        5.683378      1.237918 2022-02-28 19:00:00
184076        6.447504      1.242322 2022-02-28 20:00:00
184077        6.885220      1.246680 2022-02-28 21:00:00
184078        5.771698      1.250997 2022-02-28 22:00:00
184079        4.194956      1.258158 2022-02-28 23:00:00

[184080 rows x 3 columns]}}
dict_keys(['meter', 'curtail', 'reanalysis', 'metadata', 'analysis_type'])

In [9]:
plant

PlantData(metadata=PlantMetaData(latitude=48.452, longitude=5.588, capacity=8.2, scada=SCADAMetaData(time='time', WTUR_TurNam='WTUR_TurNam', WTUR_W='WTUR_W', WMET_HorWdSpd='WMET_HorWdSpd', WMET_HorWdDir='WMET_HorWdDir', WTUR_TurSt='WTUR_TurSt', WROT_BlPthAngVal='WROT_BlPthAngVal', WMET_EnvTmp='WMET_EnvTmp', frequency='10T', name='scada', WTUR_SupWh='WTUR_SupWh', col_map={'time': 'time', 'WTUR_TurNam': 'WTUR_TurNam', 'WTUR_W': 'WTUR_W', 'WMET_HorWdSpd': 'WMET_HorWdSpd', 'WMET_HorWdDir': 'WMET_HorWdDir', 'WTUR_TurSt': 'WTUR_TurSt', 'WROT_BlPthAngVal': 'WROT_BlPthAngVal', 'WMET_EnvTmp': 'WMET_EnvTmp', 'WTUR_SupWh': 'WTUR_SupWh'}, col_map_reversed={'time': 'time', 'WTUR_TurNam': 'WTUR_TurNam', 'WTUR_W': 'WTUR_W', 'WMET_HorWdSpd': 'WMET_HorWdSpd', 'WMET_HorWdDir': 'WMET_HorWdDir', 'WTUR_TurSt': 'WTUR_TurSt', 'WROT_BlPthAngVal': 'WROT_BlPthAngVal', 'WMET_EnvTmp': 'WMET_EnvTmp', 'WTUR_SupWh': 'WTUR_SupWh'}, dtypes={'time': <class 'numpy.datetime64'>, 'WTUR_TurNam': <class 'str'>, 'WTUR_W': <class 'float'>, 'WMET_HorWdSpd': <class 'float'>, 'WMET_HorWdDir': <class 'float'>, 'WTUR_TurSt': <class 'str'>, 'WROT_BlPthAngVal': <class 'float'>, 'WMET_EnvTmp': <class 'float'>, 'WTUR_SupWh': <class 'float'>}, units={'time': 'datetim64[ns]', 'WTUR_TurNam': None, 'WTUR_W': 'kW', 'WMET_HorWdSpd': 'm/s', 'WMET_HorWdDir': 'deg', 'WTUR_TurSt': None, 'WROT_BlPthAngVal': 'deg', 'WMET_EnvTmp': 'C', 'WTUR_SupWh': 'kWh'}), meter=MeterMetaData(time='time', MMTR_SupWh='MMTR_SupWh', frequency=Timedelta('0 days 00:10:00'), name='meter', col_map={'time': 'time', 'MMTR_SupWh': 'MMTR_SupWh'}, dtypes={'time': <class 'numpy.datetime64'>, 'MMTR_SupWh': <class 'float'>}, units={'time': 'datetim64[ns]', 'MMTR_SupWh': 'kWh'}), tower=TowerMetaData(time='time', id='id', frequency='10T', name='tower', col_map={'time': 'time', 'id': 'id'}, dtypes={'time': <class 'numpy.datetime64'>, 'id': <class 'str'>}, units={'time': 'datetim64[ns]', 'id': None}), status=StatusMetaData(time='time', id='id', status_id='status_id', status_code='status_code', status_text='status_text', frequency='10T', name='status', col_map={'time': 'time', 'id': 'id', 'status_id': 'status_id', 'status_code': 'status_code', 'status_text': 'status_text'}, dtypes={'time': <class 'numpy.datetime64'>, 'id': <class 'str'>, 'status_id': <class 'numpy.int64'>, 'status_code': <class 'numpy.int64'>, 'status_text': <class 'str'>}, units={'time': 'datetim64[ns]', 'id': None, 'status_id': None, 'status_code': None, 'status_text': None}), curtail=CurtailMetaData(time='time', IAVL_ExtPwrDnWh='IAVL_ExtPwrDnWh', IAVL_DnWh='IAVL_DnWh', frequency=Timedelta('0 days 00:10:00'), name='curtail', col_map={'time': 'time', 'IAVL_ExtPwrDnWh': 'IAVL_ExtPwrDnWh', 'IAVL_DnWh': 'IAVL_DnWh'}, dtypes={'time': <class 'numpy.datetime64'>, 'IAVL_ExtPwrDnWh': <class 'float'>, 'IAVL_DnWh': <class 'float'>}, units={'time': 'datetim64[ns]', 'IAVL_ExtPwrDnWh': 'kWh', 'IAVL_DnWh': 'kWh'}), asset=AssetMetaData(id='id', latitude='latitude', longitude='longitude', rated_power='rated_power', hub_height='hub_height', rotor_diameter='rotor_diameter', elevation='elevation', type='type', name='asset', col_map={'id': 'id', 'latitude': 'latitude', 'longitude': 'longitude', 'rated_power': 'rated_power', 'hub_height': 'hub_height', 'rotor_diameter': 'rotor_diameter', 'elevation': 'elevation', 'type': 'type'}, dtypes={'id': <class 'str'>, 'latitude': <class 'float'>, 'longitude': <class 'float'>, 'rated_power': <class 'float'>, 'hub_height': <class 'float'>, 'rotor_diameter': <class 'float'>, 'elevation': <class 'float'>, 'type': <class 'str'>}, units={'id': None, 'latitude': 'WGS84', 'longitude': 'WGS84', 'rated_power': 'kW', 'hub_height': 'm', 'rotor_diameter': 'm', 'elevation': 'm', 'type': None}), reanalysis={'merra2': ReanalysisMetaData(time='time', WMETR_HorWdSpd='WMETR_HorWdSpd', WMETR_HorWdSpdU='WMETR_HorWdSpdU', WMETR_HorWdSpdV='WMETR_HorWdSpdV', WMETR_HorWdDir='WMETR_HorWdDir', WMETR_EnvTmp='WMETR_EnvTmp', WMETR_AirDen='WMETR_AirDen', WMETR_EnvPres='surface_pressure', frequency=Timedelta('0 days 01:00:00'), name='reanalysis', col_map={'time': 'time', 'WMETR_HorWdSpd': 'WMETR_HorWdSpd', 'WMETR_HorWdSpdU': 'WMETR_HorWdSpdU', 'WMETR_HorWdSpdV': 'WMETR_HorWdSpdV', 'WMETR_HorWdDir': 'WMETR_HorWdDir', 'WMETR_EnvTmp': 'WMETR_EnvTmp', 'WMETR_AirDen': 'WMETR_AirDen', 'WMETR_EnvPres': 'surface_pressure'}, dtypes={'time': <class 'numpy.datetime64'>, 'WMETR_HorWdSpd': <class 'float'>, 'WMETR_HorWdSpdU': <class 'float'>, 'WMETR_HorWdSpdV': <class 'float'>, 'WMETR_HorWdDir': <class 'float'>, 'WMETR_EnvTmp': <class 'float'>, 'WMETR_AirDen': <class 'float'>, 'WMETR_EnvPres': <class 'float'>}, units={'time': 'datetim64[ns]', 'WMETR_HorWdSpd': 'm/s', 'WMETR_HorWdSpdU': 'm/s', 'WMETR_HorWdSpdV': 'm/s', 'WMETR_HorWdDir': 'deg', 'WMETR_EnvTmp': 'K', 'WMETR_AirDen': 'kg/m^3', 'WMETR_EnvPres': 'Pa'}), 'era5': ReanalysisMetaData(time='time', WMETR_HorWdSpd='WMETR_HorWdSpd', WMETR_HorWdSpdU='WMETR_HorWdSpdU', WMETR_HorWdSpdV='WMETR_HorWdSpdV', WMETR_HorWdDir='WMETR_HorWdDir', WMETR_EnvTmp='WMETR_EnvTmp', WMETR_AirDen='WMETR_AirDen', WMETR_EnvPres='surface_pressure', frequency=Timedelta('0 days 01:00:00'), name='reanalysis', col_map={'time': 'time', 'WMETR_HorWdSpd': 'WMETR_HorWdSpd', 'WMETR_HorWdSpdU': 'WMETR_HorWdSpdU', 'WMETR_HorWdSpdV': 'WMETR_HorWdSpdV', 'WMETR_HorWdDir': 'WMETR_HorWdDir', 'WMETR_EnvTmp': 'WMETR_EnvTmp', 'WMETR_AirDen': 'WMETR_AirDen', 'WMETR_EnvPres': 'surface_pressure'}, dtypes={'time': <class 'numpy.datetime64'>, 'WMETR_HorWdSpd': <class 'float'>, 'WMETR_HorWdSpdU': <class 'float'>, 'WMETR_HorWdSpdV': <class 'float'>, 'WMETR_HorWdDir': <class 'float'>, 'WMETR_EnvTmp': <class 'float'>, 'WMETR_AirDen': <class 'float'>, 'WMETR_EnvPres': <class 'float'>}, units={'time': 'datetim64[ns]', 'WMETR_HorWdSpd': 'm/s', 'WMETR_HorWdSpdU': 'm/s', 'WMETR_HorWdSpdV': 'm/s', 'WMETR_HorWdDir': 'deg', 'WMETR_EnvTmp': 'K', 'WMETR_AirDen': 'kg/m^3', 'WMETR_EnvPres': 'Pa'})}), analysis_type=['MonteCarloAEP'], scada=None, meter=                     MMTR_SupWh
time
2014-01-01 00:00:00  369.726013
2014-01-01 00:10:00  376.408997
2014-01-01 00:20:00  309.199005
2014-01-01 00:30:00  350.175995
2014-01-01 00:40:00  286.333008
...                         ...
2015-12-31 23:10:00  147.141006
2015-12-31 23:20:00  194.841995
2015-12-31 23:30:00  180.688004
2015-12-31 23:40:00  149.039001
2015-12-31 23:50:00  125.091003

[105120 rows x 1 columns], tower=None, status=None, curtail=                     IAVL_DnWh  IAVL_ExtPwrDnWh
time
2014-01-01 00:00:00        0.0              0.0
2014-01-01 01:00:00        0.0              0.0
2014-01-01 02:00:00        0.0              0.0
2014-01-01 03:00:00        0.0              0.0
2014-01-01 04:00:00        0.0              0.0
...                        ...              ...
2015-12-31 19:00:00        0.0              0.0
2015-12-31 20:00:00        0.0              0.0
2015-12-31 21:00:00        0.0              0.0
2015-12-31 22:00:00        0.0              0.0
2015-12-31 23:00:00        0.0              0.0

[17520 rows x 2 columns], asset=None, reanalysis={'merra2':                      WMETR_HorWdSpd  WMETR_AirDen
time
2000-09-01 00:30:00        6.638407      1.184835
2000-09-01 01:30:00        7.033765      1.186623
2000-09-01 02:30:00        7.400314      1.187641
2000-09-01 03:30:00        7.669838      1.188068
2000-09-01 04:30:00        7.805313      1.187347
...                             ...           ...
2021-08-31 19:30:00        7.220500      1.192943
2021-08-31 20:30:00        7.248846      1.196421
2021-08-31 21:30:00        7.298179      1.199264
2021-08-31 22:30:00        7.335604      1.201840
2021-08-31 23:30:00        7.245415      1.204394

[184080 rows x 2 columns], 'era5':                      WMETR_HorWdSpd  WMETR_AirDen
time
2001-03-01 00:00:00        7.370232      1.216079
2001-03-01 01:00:00        7.801492      1.217739
2001-03-01 02:00:00        8.044068      1.218205
2001-03-01 03:00:00        7.955197      1.218263
2001-03-01 04:00:00        7.789466      1.217996
...                             ...           ...
2022-02-28 19:00:00        5.683378      1.237918
2022-02-28 20:00:00        6.447504      1.242322
2022-02-28 21:00:00        6.885220      1.246680
2022-02-28 22:00:00        5.771698      1.250997
2022-02-28 23:00:00        4.194956      1.258158

[184080 rows x 2 columns]}, preprocess=None, _errors={'missing': {'scada': set(), 'meter': ['time'], 'tower': set(), 'curtail': ['time'], 'reanalysis': set(), 'asset': set(), 'reanalysis-merra2': ['time', 'WMETR_HorWdSpdV', 'surface_pressure', 'WMETR_HorWdDir', 'WMETR_HorWdSpdU', 'WMETR_EnvTmp'], 'reanalysis-era5': ['time', 'WMETR_HorWdSpdV', 'surface_pressure', 'WMETR_HorWdDir', 'WMETR_HorWdSpdU', 'WMETR_EnvTmp']}, 'dtype': {'scada': set(), 'meter': ['time'], 'tower': set(), 'curtail': ['time'], 'reanalysis': set(), 'asset': set(), 'reanalysis-merra2': ['time', 'WMETR_HorWdSpdU', 'WMETR_HorWdSpdV', 'WMETR_HorWdDir', 'WMETR_EnvTmp', 'surface_pressure'], 'reanalysis-era5': ['time', 'WMETR_HorWdSpdU', 'WMETR_HorWdSpdV', 'WMETR_HorWdDir', 'WMETR_EnvTmp', 'surface_pressure']}, 'frequency': {}, 'attributes': []}, eia={}, asset_distance_matrix=NOTHING, asset_direction_matrix=NOTHING)

In [11]:
plant.meter

                     MMTR_SupWh
time
2014-01-01 00:00:00  369.726013
2014-01-01 00:10:00  376.408997
2014-01-01 00:20:00  309.199005
2014-01-01 00:30:00  350.175995
2014-01-01 00:40:00  286.333008
...                         ...
2015-12-31 23:10:00  147.141006
2015-12-31 23:20:00  194.841995
2015-12-31 23:30:00  180.688004
2015-12-31 23:40:00  149.039001
2015-12-31 23:50:00  125.091003

[105120 rows x 1 columns]

## Future Directions

On the roadmap, we have several ideas on how to improve the PyEntr connection.

### More flexible schemas

### Directly ingest PySpark dataframes

### How to contribute?

Attend tomorrow's tutorial session!